# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 30, 760, 550))
        self.frame.setMinimumSize(QtCore.QSize(760, 550))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:20px;\n"
"border-top-left-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_main_interface = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_main_interface.setGeometry(QtCore.QRect(0, 7, 101, 41))
        self.pushButton_main_interface.setStyleSheet("#pushButton_main_interface{\n"
"border:none;\n"
"font: 9pt \"楷体\";\n"
"}\n"
"#pushButton_main_interface:hover\n"
"{\n"
"padding-bottom:5px;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_main_interface.setIcon(icon)
        self.pushButton_main_interface.setObjectName("pushButton_main_interface")
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_logout.setStyleSheet("#pushButton_logout{\n"
"border:none;\n"
"}\n"
"#pushButton_logout:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_logout.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/登录.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon1)
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.horizontalLayout_2.addWidget(self.pushButton_logout)
        self.pushButton_minimize = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_minimize.setStyleSheet("#pushButton_minimize{\n"
"border:none;\n"
"}\n"
"#pushButton_minimize:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_minimize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_minimize.setIcon(icon2)
        self.pushButton_minimize.setObjectName("pushButton_minimize")
        self.horizontalLayout_2.addWidget(self.pushButton_minimize)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_close.setStyleSheet("#pushButton_close{\n"
"border:none;\n"
"}\n"
"#pushButton_close:hover{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon3)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_2.addWidget(self.pushButton_close)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"    background-color: rgb(182, 180, 255);\n"
"    border-top-right-radius:20px;\n"
"    border-bottom-left-radius:20px\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_home = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_home.setStyleSheet("#pushButton_home{\n"
"border:none;\n"
"background-color: rgb(182, 180, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 12pt \"幼圆\";\n"
"}\n"
"#pushButton_home:hover{\n"
"    \n"
"    color: rgb(110, 255, 231);\n"
"\n"
"}\n"
"#pushButton_home:pressed{\n"
"    paddding-left:5px;\n"
"    padding-top:5px;\n"
"\n"
"}")
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout_2.addWidget(self.pushButton_home)
        self.pushButton_web = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_web.setStyleSheet("#pushButton_web{\n"
"background-color: rgb(182, 180, 255);\n"
"border:none;\n"
"    color: rgb(255, 255, 255);\n"
"font: 12pt \"幼圆\";\n"
"}\n"
"#pushButton_web:hover{\n"
"    \n"
"    color: rgb(110, 255, 231);\n"
"\n"
"}\n"
"#pushButton_web:pressed{\n"
"    paddding-left:5px;\n"
"    padding-top:5px;\n"
"\n"
"}")
        self.pushButton_web.setObjectName("pushButton_web")
        self.verticalLayout_2.addWidget(self.pushButton_web)
        self.pushButton_my = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_my.setStyleSheet("#pushButton_my{\n"
"background-color: rgb(182, 180, 255);\n"
"border:none;\n"
"    color: rgb(255, 255, 255);\n"
"font: 12pt \"幼圆\";\n"
"}\n"
"#pushButton_my:hover{\n"
"    \n"
"    color: rgb(110, 255, 231);\n"
"\n"
"}\n"
"#pushButton_my:pressed{\n"
"    paddding-left:5px;\n"
"    padding-top:5px;\n"
"\n"
"}")
        self.pushButton_my.setObjectName("pushButton_my")
        self.verticalLayout_2.addWidget(self.pushButton_my)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_home)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.page_home)
        self.label.setStyleSheet("\n"
"color: rgb(120, 122, 255);\n"
"border:1px solid black;\n"
"border-radius:5px;\n"
"font: 12pt \"楷体\";")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.page_home)
        self.page_web = QtWidgets.QWidget()
        self.page_web.setObjectName("page_web")
        self.frame_8 = QtWidgets.QFrame(self.page_web)
        self.frame_8.setGeometry(QtCore.QRect(60, 40, 380, 390))
        self.frame_8.setMinimumSize(QtCore.QSize(380, 390))
        self.frame_8.setMaximumSize(QtCore.QSize(380, 390))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_github = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_github.setStyleSheet("\n"
"#pushButton_github{\n"
"border:none;\n"
"font: 12pt \"Cambria Math\";}\n"
"#pushButton_github:pressed{\n"
"\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_github.setIcon(icon4)
        self.pushButton_github.setObjectName("pushButton_github")
        self.verticalLayout_4.addWidget(self.pushButton_github)
        self.pushButton_claude = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_claude.setStyleSheet("\n"
"#pushButton_claude{\n"
"border:none;\n"
"font: 12pt \"Cambria Math\";}\n"
"#pushButton_claude:pressed{\n"
"\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/cluster.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_claude.setIcon(icon5)
        self.pushButton_claude.setObjectName("pushButton_claude")
        self.verticalLayout_4.addWidget(self.pushButton_claude)
        self.stackedWidget.addWidget(self.page_web)
        self.page_my = QtWidgets.QWidget()
        self.page_my.setObjectName("page_my")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_my)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.page_my)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_2 = QtWidgets.QLabel(self.frame_11)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 111, 20))
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 12pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit_password1 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_password1.setText("")
        self.lineEdit_password1.setObjectName("lineEdit_password1")
        self.verticalLayout_7.addWidget(self.lineEdit_password1)
        self.lineEdit_password2 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_password2.setText("")
        self.lineEdit_password2.setObjectName("lineEdit_password2")
        self.verticalLayout_7.addWidget(self.lineEdit_password2)
        self.pushButton_confirm_password = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_confirm_password.setStyleSheet("#pushButton_password_confirm:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;}")
        self.pushButton_confirm_password.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/确认.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_confirm_password.setIcon(icon6)
        self.pushButton_confirm_password.setObjectName("pushButton_confirm_password")
        self.verticalLayout_7.addWidget(self.pushButton_confirm_password, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.page_my)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_9)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_2.addWidget(self.page_2)
        self.horizontalLayout_5.addWidget(self.stackedWidget_2)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.page_my)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_main_interface.setText(_translate("MainWindow", "主界面"))
        self.pushButton_home.setText(_translate("MainWindow", "首页"))
        self.pushButton_web.setText(_translate("MainWindow", "推荐网址"))
        self.pushButton_my.setText(_translate("MainWindow", "我的"))
        self.label.setText(_translate("MainWindow", "欢迎登录我的界面"))
        self.pushButton_github.setText(_translate("MainWindow", "Github"))
        self.pushButton_claude.setText(_translate("MainWindow", "Claude"))
        self.label_2.setText(_translate("MainWindow", "修改密码"))
        self.lineEdit_password1.setPlaceholderText(_translate("MainWindow", "密码："))
        self.lineEdit_password2.setPlaceholderText(_translate("MainWindow", "确认密码："))
import res_rc
